Создаст файл functions и добавит его в файл index. В файле function п…
htmlacademy-javascript/2275323-kekstagram-2 pull request #3
Opened 2024-11-09 14:22 UTC by dendy01

Создал файл functions.js, там прописал всю логику работы функций, далее подключил его в файле index.html, использовал атрибут synс, так как мы ни как не взаимодействуем с вёрсткой

2024-11-11 00:04 UTC, fyvfyv requested changes

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +}
👍 Отлично, но давай попробуем подумать над алгоритмом работы функции и постараться оптимизировать его. Например, можно задать пару вопросов:
1. Можно или обойтись без преобразований в массив и обратно?
2. Нужна ли вторая строка или можно обойтись одной?

Попробуй решить эту задачу «на бумаге», где нет лишних типов данных, абстракций и т. д. И опиши алгоритм проверки, потом попробуй написать код для этого алгоритма и посмотреть, что можно оптимизировать.

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +// }
Ненужный код надо удалять

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +function maxLengthStr(str, maxLength) {
Имя функции должно содержать глагол. [Критерий Б6](https://up.htmlacademy.ru/javascript-individual/2/criteries#b6)

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +    if (!Number.isNaN(+str[i])) {
На всякий случай оставлю [ссылку](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#description), где описана разница между `Number.isNaN` и `isNaN`. Тут нет ошибки, просто для расширения кругозора

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +  return +strNumber.replaceAll(' ', '');
А для чего здесь `replaceAll(' ', '');`?

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +function getNumber(str) {
Функция неправильно отработает на случае с десятичной дробью

2024-11-11 00:04 UTC, fyvfyv commented on js/functions.js
> +  if (+strNumber === 0) {
А в чём разница между `parseInt` и `+`. И почему в функции ты взял второе?

2024-11-11 14:11 UTC, dendy01 commented on js/functions.js
> +function getNumber(str) {
Я согласен, но ведь и в условие тоже игнорируется десятичная дробь, имяФункции('1 кефир, 0.5 батона'); // 105
В любом случае, я поправил, сейчас буду заливать изменения

2024-11-11 14:24 UTC, fyvfyv commented on js/functions.js
> +function getNumber(str) {
Если что, то я имел в виду вот этот кейс:
`имяФункции(1.5);  // 15`
твоя реализация возвращала `1.5` а не `15`

2024-11-11 15:36 UTC, dendy01 commented on js/functions.js
> +function getNumber(str) {
Понял, принял, изменения готоры)

2024-11-11 18:46 UTC, fyvfyv requested changes
Если есть сложности, с пониманием кода или комментариев, пиши и можем заскочить на звонок

2024-11-11 18:46 UTC, fyvfyv commented on js/functions.js
> +  const digits = '0123456789';
Какой-то сильно хардкодный вариант вышел. Ещё и довольно неоптимизированный, потому что ты для каждой цифры проходишься по всему массиву. А зачем ты это изменил?

2024-11-11 18:46 UTC, fyvfyv commented on js/functions.js
> +}
Так, а тут давай вернёмся к первому [комментарию](https://github.com/htmlacademy-javascript/2275323-kekstagram-2/pull/3#discussion_r1835818943) и посмотрим, изменилось ли вообще что-нибудь в логике работы функции?

2024-11-11 19:29 UTC, dendy01 commented on js/functions.js
> +}
Логика не изменилась, просто избавились от лишних переменных

2024-11-13 09:47 UTC, fyvfyv approved these changes

2024-11-13 09:48 UTC, merged